### PR TITLE
Rails 5 support 2

### PR DESCRIPTION
**Pull request by malachaifrazier**
Rails 5 upgrade. Yes, I broke a rule by committing changes to the gemspec, but I didn't change the version number.

### CODE REVIEW

**Comment by malachaifrazier** [comment]
Closes https://github.com/mbulat/plutus/issues/72

**Comment by pjohnmeyer** [comment]
I would prefer if the changes to support Rails 5 continue to support Rails 4. Is that not the plan for this gem?

**Comment by tenshiAMD** [comment]
@mbulat, any thoughts with the Rails 5 support?

**Comment by amingilani** [comment]
Hello, just a random person passing by saying thank you for making this gem, and thank you contributor for adding Rails 5. I just discovered this gem and it's wonderful! I just wish I could use it for a client's Rails 5 application.

**Comment by przbadu** [comment]
Hello, thank you guys for this wonderful gem, any luck on support for `rails 5`.

**Comment by martyphee** [comment]
I've been playing around with this a bit and a couple questions.

Why were you removing the STI?

If that is removed then Rails won't know how to query the tables shown in the last comment.

**Comment by mbulat** [comment]
Thanks for the PR and all the comments. I've looked through everything and decided to implement Rails5 support while trying to change as little as possible. I've pushed up a build at https://github.com/mbulat/plutus/tree/rails5. This should be compatible with both Rails 4 and 5, and doesn't change STI or anything else.

Please let me know how it tests out, and I'll merge into master if it looks good.

**Comment by mbulat** [comment]
The rails5 branch has been merged into master. New gem version 0.13 is live on rubygems

Thanks everyone!

**Pull request closed without merging**
