### PR TITLE
Documentation style consistency improvement

### PR DESCRIPTION
**Pull request by rthbound**
I was peeking at a few models and noticed one whose documentation wasn't as complete as the others

- adds return info
- makes description more consistent

### CODE REVIEW

**Comment by mbulat** [comment]
Merged into develop via 89d0c9f7deafbd3c386f200e6d165533768eb74b

**Comment by rthbound** [comment]
@mbulat while you're awake... I was looking at those models because they look very similar (they being: liabilities, expenses, equities, assets).

Especially, the class method, #balance... Would you consider refactoring this code to avoid the duplication, or is it purposefully duplicated for clarity?

The instance method #balance is also quite similar. It seems you could refactor the occurrences of that instance method as well.  Maybe use a class attribute on Account's subclasses to drive an instance method defined on Account.

An example of what the Liability model might look like after the refactoring:

Minimally:
```ruby
module Plutus
  # The Liability class is an account type used to represents debts owed to outsiders.
  #
  # === Normal Balance
  # The normal balance on Liability accounts is a *Credit*.
  #
  # @see http://en.wikipedia.org/wiki/Liability_(financial_accounting) Liability
  #
  # @author Michael Bulat
  class Liability < Account
    self.is_contra_by_nature = true
  end
end
```

or to retain the same clarity in your documentation:
```ruby
module Plutus
  # The Liability class is an account type used to represents debts owed to outsiders.
  #
  # === Normal Balance
  # The normal balance on Liability accounts is a *Credit*.
  #
  # @see http://en.wikipedia.org/wiki/Liability_(financial_accounting) Liability
  #
  # @author Michael Bulat
  class Liability < Account
    self.is_contra_by_nature = true

    # The balance of the account.
    #
    # Liability accounts have normal credit balances, so the debits are subtracted from the credits
    # unless this is a contra account, in which credits are subtracted from debits
    #
    # @example
    #   >> liability.balance
    #   => #<BigDecimal:103259bb8,'0.2E4',4(12)>
    #
    # @return [BigDecimal] The decimal value balance
    def balance
      super
    end

    # This class method is used to return
    # the balance of all Liability accounts.
    #
    # Contra accounts are automatically subtracted from the balance.
    #
    # @example
    #   >> Plutus::Liability.balance
    #   => #<BigDecimal:1030fcc98,'0.82875E5',8(20)>
    #
    # @return [BigDecimal] The decimal value balance
    def self.balance
      super
    end
  end
end
```

**Comment by rthbound** [comment]
@mbulat You'd probably use something like `self.normal_balance_is_credit=true` not `self.is_contra_by_nature`.... ^

**Comment by mbulat** [comment]
@rthbound I like your version that retains the documentation clarity. If you submit a pull request for that to develop, i'll go ahead and merge. Thanks!

**Pull request closed without merging**
